CREATE TABLE [stng].[CMDS_Category_Map](
	[UniqueID] [bigint] IDENTITY(1,1) NOT NULL,
	[CMDSID] [uniqueidentifier] NOT NULL,
	[Category] [uniqueidentifier] NOT NULL,
	[RAB] [varchar](20) NOT NULL,
	[RAD] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UniqueID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [CNST_stng_CMDS_Category_Map_Unique] UNIQUE NONCLUSTERED 
(
	[CMDSID] ASC,
	[Category] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [stng].[CMDS_Category_Map] ADD  DEFAULT ([stng].[getbptime](getdate())) FOR [RAD]
GO

ALTER TABLE [stng].[CMDS_Category_Map]  WITH CHECK ADD FOREIGN KEY([Category])
REFERENCES [stng].[CMDS_Category] ([UniqueID])
GO

ALTER TABLE [stng].[CMDS_Category_Map]  WITH CHECK ADD FOREIGN KEY([CMDSID])
REFERENCES [stng].[CMDS_Goal] ([UniqueID])
GO

ALTER TABLE [stng].[CMDS_Category_Map]  WITH CHECK ADD FOREIGN KEY([RAB])
REFERENCES [stng].[Admin_User] ([EmployeeID])
GO


