CREATE view [stng].[VV_ER_WO] as
select a.UniqueID, b.UniqueID as ERID,  a.[ER],
a.[WONUM],
a.[WOHeader],
a.[ExecDate],
a.[PMER],
a.[WOType],
a.[WOTitle],
a.[WOGroup],
a.[PCTR],
a.[ScheduleBacklog],
a.[ScheduleGrade],
a.[WOStatus],
a.[OnlineReporting],
a.[Tweek],
a.[OperatorChallenge],
a.[WOOriginDate],
a.[WOAge],
a.[WOPRIORITY],
a.[Outage],
a.[OutageStart],
a.[OutageEnd],
a.[HighPriority],
a.[LowPriority],
a.[OutageRank],
a.[CNOPriority],
a.[EmergentBacklog],
a.[EmergentBacklogRender],
a.[PHCFlag],
a.[Projectid],
a.[M05TCD],
a.[M16TCD],
a.[InventoryWO],
a.[ProjectRank],
a.[CanceledWO]
from stngetl.ER_SupportWO as a
inner join stng.ER_Main_Temp as b on a.ER = b.ER
where a.WONUM is not null