DELETE FROM stng.Budgeting_SDQRelatedTOQ
DELETE FROM stng.Budgeting_LinkedTOQ_Mapping
DELETE FROM stng.TOQ_Band
DELETE FROM stng.TOQ_Binning
DELETE FROM Stng.TOQ_Child
DELETE FROM stng.TOQ_ClassV
DELETE FROM stng.TOQ_Correspondence
DELETE FROM stng.TOQ_CostSummary
DELETE FROM stng.TOQ_EmergentResolveLog
DELETE FROM stng.TOQ_EmergentStatusLog
DELETE FROM stng.TOQ_EmergentLink
DELETE FROM stng.TOQ_Emergent
DELETE FROM stng.TOQ_EmergentDetail
DELETE FROM stng.TOQ_FieldChangeLog
DELETE FROM stng.TOQ_Partial
DELETE FROM stng.TOQ_RAM_AllFields
DELETE FROM stng.TOQ_RAM_BudgetForm_BudgetSummary
DELETE FROM stng.TOQ_RAM_BudgetForm_DesignDiscipline
DELETE FROM stng.TOQ_RAM_BudgetForm_DesignSupport
DELETE FROM stng.TOQ_RAM_BudgetForm_CostAllocation
DELETE FROM stng.TOQ_RAM_Revision
DELETE FROM stng.TOQ_RAM_VendorComparison
DELETE FROM stng.TOQ_Rework
DELETE FROM stng.TOQ_StatusLog
DELETE FROM stng.TOQ_VendorStatusLog
DELETE FROM stng.TOQ_VendorTOQReason
DELETE FROM stng.TOQ_VendorAssigned
DELETE FROM stng.TOQ_StatusLog
DELETE FROM stng.TOQ_Main
DELETE FROM stng.TOQ_ClassVMain