CREATE TABLE stng.TOQ_FieldChangeLog
(
	UniqueID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	TOQID UNIQUEIDENTIFIER REFERENCES stng.TOQ_Main(UniqueID),
	[RecordTypeID] UNIQUEIDENTIFIER REFERENCES stng.Common_ValueLabel(UniqueID),
	[ChangeTypeID] UNIQUEIDENTIFIER REFERENCES stng.Common_ValueLabel(UniqueID),
	[Group] NVARCHAR(255),
	FieldName NVARCHAR(255),
	FromValue NVARCHAR(4000),
	ToValue NVARCHAR(4000),
	CreatedBy VARCHAR(20) REFERENCES stng.Admin_User(EmployeeID),
	CreatedDate DATETIME DEFAULT GETDATE()
)