CREATE TABLE [stng].[TOQ_QAProgram](
	[UniqueID] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	[TOQ_EmergentID] UNIQUEIDENTIFIER REFERENCES stng.TOQ_Emergent(UniqueID) ON DELETE CASCADE,
	[TOQ_MainID] UNIQUEIDENTIFIER REFERENCES stng.TOQ_Main(UniqueID) ON DELETE CASCADE,
	[QAProgramID] UNIQUEIDENTIFIER REFERENCES stng.Common_ValueLabel(UniqueID),
)