CREATE TABLE stng.TOQ_Correspondence(
	UniqueID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	ParentUID UNIQUEIDENTIFIER REFERENCES stng.Correspondence(UniqueID),
	TOQMainID UNIQUEIDENTIFIER REFERENCES stng.TOQ_Main(UniqueID) ON DELETE CASCADE NOT NULL,
	TypeID UNIQUEIDENTIFIER REFERENCES stng.Common_ValueLabel(UniqueID),
	Subject NVARCHAR(1000),
	Detail NVARCHAR(2000),
	DetailLong NVARCHAR(4000),
	QuestionAnswer VARCHAR(2) DEFAULT 'Q',
	ResponseDueDate AS CASE WHEN QuestionAnswer = 'Q' THEN CAST(DATEADD(Day,2,CreatedDate) AS DATE) ELSE NULL END,
	CreatedDate DATETIME DEFAULT stng.GetDate(),
	CreatedBy VARCHAR(20) REFERENCES  stng.Admin_User(EmployeeID),
	FromVOE NVARCHAR(255)
)