CREATE TABLE [stng].[Common_ETLModule](
	[ETLID] [uniqueidentifier] NOT NULL,
	[ModuleID] [int] NOT NULL,
	[RAB] [nvarchar](60) NOT NULL,
	[RAD] [datetime] NOT NULL,
	[MId] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [CNST_Common_ETLModule_Unique] UNIQUE NONCLUSTERED 
(
	[ETLID] ASC,
	[ModuleID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [stng].[Common_ETLModule] ADD  DEFAULT (getdate()) FOR [RAD]
GO

ALTER TABLE [stng].[Common_ETLModule]  WITH CHECK ADD FOREIGN KEY([ETLID])
REFERENCES [stng].[Common_ETLMap] ([ETLID])
GO

ALTER TABLE [stng].[Common_ETLModule]  WITH CHECK ADD FOREIGN KEY([ModuleID])
REFERENCES [stng].[Admin_Module] ([ModuleID])
GO