CREATE TABLE [stng].[Common_ETLMap](
	[ETLID] [uniqueidentifier] NOT NULL,
	[ETLName] [nvarchar](255) NOT NULL,
	[ETLDescription] [nvarchar](500) NULL,
	[CreatedBy] [nvarchar](255) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ETLID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ETLName] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [stng].[Common_ETLMap] ADD  DEFAULT (newid()) FOR [ETLID]
GO

ALTER TABLE [stng].[Common_ETLMap] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
