services:
    stingrayapi:
        image: ${CONTAINERNAME}/stable:latest
        build:
            context: .
            dockerfile: dockerfile
            args: 
                ENVNAME: ${ENVNAME}