EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Allied',@Value='AECO',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Alithya',@Value='ALIT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='BWXT NEC',@Value='BWXT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='BWXT Cambridge',@Value='BWXTC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Candu',@Value='CANDU',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Framatome',@Value='FRAM',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Hatch',@Value='HATC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='KCI',@Value='KCI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Kinectrics NSS',@Value='KI NSS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Kinectrics MS',@Value='KI MS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Kinectrics NCL',@Value='KI NCL',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Kinectrics PMPC',@Value='KI PMPC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='LRI',@Value='LRI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='NA Engineering',@Value='NAE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='NPX',@Value='NPX',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Promation',@Value='PROM',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='RCMT',@Value='RCMT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Rolls Royce',@Value='ROLLS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='S&L',@Value='SAL',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Sargent Lundy',@Value='SARGL',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Siemens',@Value='SIEM',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='SNC Lavalin',@Value='SNC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Tetra Tech',@Value='TT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Various',@Value='VAR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Westinghouse',@Value='WEST',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Westinghouse Canada',@Value='WESTC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='Admin', @Group='Vendor',@Field='Vendor',@Label='Worley Parsons',@Value='WORL',@CreatedBy='619704'