
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='VarianceComment',@Value1='AMOT',@Label='AMOT SOW revision',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='VarianceComment',@Value1='DesignError',@Label='Design error/rework',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='VarianceComment',@Value1='EstimatingError',@Label='Estimating error',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='VarianceComment',@Value1='LAMP3',@Label='Recently accelerated into LAMP3',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='VarianceComment',@Value1='Other',@Label='Other',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='PBRF',@Field='ProjectType',@Value1='IN',@Label='OMA - Inage',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='PBRF',@Field='ProjectType',@Value1='PLANOUT',@Label='OMA - Planned Outage',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='2030',@Label='Capital - Project 2030',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='ASSET',@Label='Capital - Asset Management',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='DIG',@Label='Capital - Engineering Digitization',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='INIT',@Label='OMA - Initiatives',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='ISO',@Label='Capital - Isotopes',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='MCR',@Label='Capital - MCR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='OUT',@Label='Capital - Outage',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='STRAT',@Label='Capital - Strategic',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='SUS',@Label='Capital - Sustaining',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC',@Group='SDQ',@Field='ProjectType',@Value1='NA',@Label='NA (Legacy)',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Scope',@Label='Force Majeure (Acts of Nature)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Scope',@Label='Scope change (those that could not have been anticipated at the time of preparation of original task estimate)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Scope',@Label='Approach change (directed by customer)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Scope',@Label='Business drivers change (budget, deployment schedule, time constraints, business priorities, etc.)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Scope',@Label='Phase change of a project.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Scope',@Label='Variances created through the actions or lack of action by customers/PM.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Scope',@Label='Customers/PM provide incomplete or unstable requirements, adding new constraints, or through lack of timely decisions, work authorizations or contractual funding.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Trend',@Label='Changes that were/could have been anticipated during original task estimate.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Trend',@Label='Poor estimating, performance, risk or resource management.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Trend',@Label='Risk is encountered and mitigation steps need to be enacted.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Trend',@Label='Risk is encountered and estimate uncertainty dollars need to be spent.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Trend',@Label='Project cost projections are above a certain threshold.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Trend',@Label='Project is under budget or schedule.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Trend',@Label='Vendor is late on deliverable.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Trend',@Label='Resource is pulled from project.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Reason',@Field='Trend',@Label='Re-sequence of implementation schedule (unless it costs more)',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='MinorChangeType',@CreatedBy='619704',@Label='Header General Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='MinorChangeType',@CreatedBy='619704',@Label='Problem Definition Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='MinorChangeType',@CreatedBy='619704',@Label='Current Scope Definition Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='MinorChangeType',@CreatedBy='619704',@Label='Assumptions Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='MinorChangeType',@CreatedBy='619704',@Label='Risk Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='MinorChangeType',@CreatedBy='619704',@Label='Related TOQ Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='MinorChangeType',@CreatedBy='619704',@Label='CII SDS Code Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='MinorChangeType',@CreatedBy='619704',@Label='CV SDS Code Update'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Project Title Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='RC Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Problem Statement Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Scope Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Installation Date Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Funding Source Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Installation Date Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Station Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Information References Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Year 1 Cost Estimation Update'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='MinorChangeType',@CreatedBy='619704',@Label='Year 2 Cost Estimation Update'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Assessing (Maintenance)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='BA EFIN - Electrical and I&C',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='BA EFIN - Mechanical',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='BB EFIN - Electrical and I&C',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='BB EFIN - Mechanical',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Centralized Execution Team',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Civil and Security Design',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Component Design Electrical I&C',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Component Design Mechanical',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Computer Design',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Control Design',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='DES Resource',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Design Programs',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Design Services',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Digital Engineering',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Drafting',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Electrical Design',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Eng Support - ERI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Eng Support - Outages Engineering',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Engineering Business Support',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Fuel Handling Engineering (ENGP)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Fuel Management and Reactor Physics',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='General',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Governance and Oversight',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='I&C and Electrical Design Projects',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='LifeX Engineering',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Major Components Engineering Programs',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='MCR Capital Projects',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='MCR Field Engineering Balance of Plant',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='MCR Field Engineering Feeders',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='MCR Field Engineering Fuel Channels',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='MCR Field Engineering Steam Generators',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Mechanical Design',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Permit Execution Override',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='PMC Engineering',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Pressure Boundary and Piping',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Reactor Design',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Reactor Safety Support',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Reactor Tooling and Fuel Handling',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Reactory Safety',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Site Services Engineering',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Specialized Tool Engineering',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Station Engineering Special Projects',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Supply Chain (BA)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Supply Chain (BB)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Supply Chain (MCR BA)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Supply Chain (MCR BB)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Supply Chain (Projects)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Sys Eng - Balance of Plant Systems',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Sys Eng - Electrical and I&C Components',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Sys Eng - Electrical and I&C Systems',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Sys Eng - Mechanical Components',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='Section',@Field='Name',@Label='Sys Eng - Nuclear Systems',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='ChecklistType',@Value='VERIFIER',@Label='Verification',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='ChecklistType',@Value='SELF',@Label='Self',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='ChecklistType',@Value='PLANNER',@Label='Planner',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='ChecklistType',@Value='LEGACY_VERIFIER',@Label='Verification',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='ChecklistType',@Value='OE',@Label='OE',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='1',@Value1='Scope',@Label='Does the current scope description adequately describe what is being commited to in this phase of work?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='2',@Value1='Scope',@Label='In the Detailed Scope section, is there reference to relevant engineering documents (DCP, DCN, Design Plan, Design Requirement, etc)?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='3',@Value1='Scope',@Label='Is the cost and schedule assumptions section filled out completely and are all project specific assumptions specific and reasonable?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='4',@Value1='Scope',@Label='Subprojects have been created where Detailed Engineering, Execution and/or Closeout are taking place in multiple units',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='5',@Value1='Scope',@Label='Is the next phase DQ scheduled?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='1',@Value1='Schedule',@Label='Are LOE (consulting TOQ, PMPC, OLW support) start and finish dates aligned with the project schedule?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='2',@Value1='Schedule',@Label='Is Critical Path well-defined and understood?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='3',@Value1='Schedule',@Label='Are all outage milestone links correctly identified and coded?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='4',@Value1='Schedule',@Label='Are new fragnets copied from the most recent DEDWBS template?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='5',@Value1='Schedule',@Label='Activities and Commitments not required from the Template are marked as “NR” and logic adjusted accordingly',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='6',@Value1='Schedule',@Label='Phase Milestone (PM milestones) for CD release of funds (i.e CD1, CD2), have successors tied correctly into the schedule',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='7',@Value1='Schedule',@Label='Indirect deliverables have been properly added under a parent Level 6 “Summary Direct Deliverable” heading (i.e., Other Conceptual,Preliminary or Detailed Deliverable)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='8',@Value1='Schedule',@Label='XXX placeholders (i.e., DCNXXX) have been replaced with proper information.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='9',@Value1='Schedule',@Label='All DQ and NDQ commitment names have been updated and are unique (we cannot have a commitment name repeated with the exact same name in any one project)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='10',@Value1='Schedule',@Label='Where execution is taking place during an outage, Detailed Eng is complete 1 year prior to the outage start date (to meet Outage Milestone 9) and includes Drafting',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='11',@Value1='Schedule',@Label='DCN closeout, if required, has 88-day duration, followed by DCP closeout with 22-day duration, followed by Project Closeout fragnet',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='1',@Value1='Cost',@Label='Do all completed phases have zero remaining cost? ',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='2',@Value1='Cost',@Label='Has the Total EAC changed since the previous SDQ/SDQ revisions? If yes, has sufficient justification been provided within the SDQ?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='3',@Value1='Cost',@Label='Is the Total EAC within the LAMP EAC? If no, has sufficient justification been provided with the SDQ?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='1',@Value1='Resourcing',@Label='Durations / Dates and Labour Units reviewed, and changes made where necessary.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='2',@Value1='Resourcing',@Label='Changes to labour units do not exceed "7 to 70" rule.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='3',@Value1='Resourcing',@Label='Labour units do not exceed 70% of daily max hours for a resource',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='4',@Value1='Resourcing',@Label='All activities with labour units have a resource name added to the activity.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='5',@Value1='Resourcing',@Label='Generic Resources are replaced with proper resource names for any activities appearing on crew sheets',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='1',@Value1='Contracts',@Label='Is the schedule aligned with the vendor TOQ commitments and/or deliverable submission dates?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='2',@Value1='Contracts',@Label='Is PMPC cost sufficient to cover PCS and planner effort as well as spread charges for the duration of the project',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='3',@Value1='Contracts',@Label='Is the TOQ total request within the SDQ aligned with the Vendor TOQ total value?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='4',@Value1='Contracts',@Label='Engineering Deliverable Contract(s) have been added under the correct WBS in the schedule, with correct dates/duration and budget aligned with the TOQ.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='5',@Value1='Contracts',@Label='Other Contracts (i.e., Consulting Contract) have been added to the schedule to account for any MSC resources not generating a budget at the activity level.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='6',@Value1='Contracts',@Label='PMPC activities have been added to support each Design Phase.  Budget has been reviewed and updated according to Project Controls standard (i.e. 13% of DED and vendor budget)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='1',@Value1='Class V',@Label='Is the Class V estimate broken down by unit in the SDS table?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='2',@Value1='Class V',@Label='Does the Class V portion of the schedule cover the remaining life of the project?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='3',@Value1='Class V',@Label='Class V fragnets have been added for any future design phases. Durations adjusted according to the Standard Engineering Timelines and Complexity assigned to the project',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='4',@Value1='Class V',@Label='Execution Class V fragnets have the Unit and Outage / Online included in the WBS name.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='SelfChecklist',@Value='5',@Value1='Class V',@Label='Where Class V activities exist, there is a Design Plan, TOQ/TDS (if external), and ‘DQ for Next Phase WBS. (i.e.  Design Plan Authorized  -> TDS/TOQ  ->  DQ)',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='1',@Value1='Scope',@Label='Does the current scope description adequately describe what is being commited to in this phase of work?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='2',@Value1='Scope',@Label='In the Detailed Scope section, is there reference to relevant engineering documents (DCP, DCN, Design Plan, Design Requirement, etc)?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='3',@Value1='Scope',@Label='Is the cost and schedule assumptions section filled out completely and are all project specific assumptions specific and reasonable?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='4',@Value1='Scope',@Label='Subprojects have been created where Detailed Engineering, Execution and/or Closeout are taking place in multiple units',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='1',@Value1='Schedule',@Label='Where execution is taking place during an outage, Detailed Eng is complete 1 year prior to the outage start date (to meet Outage Milestone 9) and includes Drafting',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='2',@Value1='Schedule',@Label='DCN closeout, if required, has 88-day duration, followed by DCP closeout with 22-day duration, followed by Project Closeout fragnet',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='1',@Value1='Cost',@Label='Do all completed phases have zero remaining cost?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='2',@Value1='Cost',@Label='Has the Total EAC changed since the previous SDQ/SDQ revisions? If yes, has sufficient justification been provided within the SDQ?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='3',@Value1='Cost',@Label='Is the Total EAC within the LAMP EAC? If no, has sufficient justification been provided with the SDQ?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='1',@Value1='Resourcing',@Label='Durations / Dates and Labour Units reviewed, and changes made where necessary.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='2',@Value1='Resourcing',@Label='Labour units do not exceed 70% of daily max hours for a resource',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='3',@Value1='Resourcing',@Label='Generic Resources are replaced with proper resource names for any activities appearing on crew sheets',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='1',@Value1='Contracts',@Label='Is PMPC cost sufficient to cover PCS and planner effort as well as spread charges for the duration of the project',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='2',@Value1='Contracts',@Label='Is the TOQ total request within the SDQ aligned with the Vendor TOQ total value?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='1',@Value1='Class V',@Label='Is the Class V estimate broken down by unit in the SDS table?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='2',@Value1='Class V',@Label='Does the Class V portion of the schedule cover the remaining life of the project?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='VerificationChecklist',@Value='3',@Value1='Class V',@Label='Where Class V activities exist, there is a Design Plan, TOQ/TDS (if external), and ‘DQ for Next Phase WBS. (i.e.  Design Plan Authorized  -> TDS/TOQ  ->  DQ)',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='1',@Value1='Scope',@Label='Is the next phase DQ scheduled?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='1',@Value1='Schedule',@Label='Are LOE (consulting TOQ, PMPC, OLW support) start and finish dates aligned with the project schedule?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='2',@Value1='Schedule',@Label='Is Critical Path well-defined and understood?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='3',@Value1='Schedule',@Label='Are all outage milestone links correctly identified and coded?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='4',@Value1='Schedule',@Label='Are new fragnets copied from the most recent DEDWBS template?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='5',@Value1='Schedule',@Label='Activities and Commitments not required from the Template are marked as “NR” and logic adjusted accordingly',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='6',@Value1='Schedule',@Label='Phase Milestone (PM milestones) for CD release of funds (i.e CD1, CD2), have successors tied correctly into the schedule',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='7',@Value1='Schedule',@Label='Indirect deliverables have been properly added under a parent Level 6 “Summary Direct Deliverable” heading (i.e., Other Conceptual,Preliminary or Detailed Deliverable)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='8',@Value1='Schedule',@Label='XXX placeholders (i.e., DCNXXX) have been replaced with proper information.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='9',@Value1='Schedule',@Label='All DQ and NDQ commitment names have been updated and are unique (we cannot have a commitment name repeated with the exact same name in any one project)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='1',@Value1='Resourcing',@Label='Changes to labour units do not exceed "7 to 70" rule.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='2',@Value1='Resourcing',@Label='All activities with labour units have a resource name added to the activity.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='1',@Value1='Contracts',@Label='Is the schedule aligned with the vendor TOQ commitments and/or deliverable submission dates?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='2',@Value1='Contracts',@Label='Engineering Deliverable Contract(s) have been added under the correct WBS in the schedule, with correct dates/duration and budget aligned with the TOQ.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='3',@Value1='Contracts',@Label='Other Contracts (i.e., Consulting Contract) have been added to the schedule to account for any MSC resources not generating a budget at the activity level.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='4',@Value1='Contracts',@Label='PMPC activities have been added to support each Design Phase.  Budget has been reviewed and updated according to Project Controls standard (i.e. 13% of DED and vendor budget)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='1',@Value1='Class V',@Label='Class V fragnets have been added for any future design phases. Durations adjusted according to the Standard Engineering Timelines and Complexity assigned to the project',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='PlannerChecklist',@Value='2',@Value1='Class V',@Label='Execution Class V fragnets have the Unit and Outage / Online included in the WBS name.',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='OEChecklist',@Value1='Scope',@Label='Does the current scope description adequately describe what is being committed to in this phase of work?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='OEChecklist',@Value1='Schedule',@Label='Is the overall schedule sequencing and logic accurate?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='OEChecklist',@Value1='Scope',@Label='Is the cost and schedule assumptions section filled out completely and are all project specific assumptions specific and reasonable?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='OEChecklist',@Value1='Schedule',@Label='Activities and Commitments not required from the template are marked as “NR” and logic adjusted accordingly?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='OEChecklist',@Value1='Schedule',@Label='XXX placeholders (i.e DCN XXXXX) have been replaced with proper information',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='OEChecklist',@Value1='Resourcing',@Label='Generic Resources are replaced with proper resource names for any activities appearing on crewsheets',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='OEChecklist',@Value1='Schedule',@Label='Has SM and/or DM-EP Approval been obtained for any non-standard scheduling practices?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='OEChecklist',@Value1='Scope',@Label='Has the SDQ been socialized with the Project Customer?',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='OEChecklist',@Value1='Resourcing',@Label='Have all Project Stakeholders been identified, contacted, and confirmed to be available to support the project?',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Initiation',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Conceptual Design (Development)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Preliminary Design (Definition)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Detailed Design (Preparation)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Engr Construction Support (Execution)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Closeout',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Initiated',@Value='INIT' ,@Sort=10,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting DivM Approval',@Value='ADMA' ,@Sort=20,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting OE Approval',@Value='AOEA' ,@Sort=30,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting SM(s) Approval',@Value='ASMA' ,@Sort=40,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting SM(s) Approval',@Value='ASMA_APP' ,@Sort=45,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Approved, Partial Release',@Value='APRE' ,@Sort=50,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting Customer Approval',@Value='ACAPP' ,@Sort=60,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting PM Approval',@Value='APJMA' ,@Sort=65,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting Prog.M Approval',@Value='APGMA' ,@Sort=67,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Approved, Full Release',@Value='AFRE' ,@Sort=70,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting DM EP Approval',@Value='ADPA' ,@Sort=80,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Correction Required',@Value='CORR' ,@Sort=90,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting Verification',@Value='AVER' ,@Sort=100,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Processing P6',@Value='PRP6' ,@Sort=110,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Canceled',@Value='CANC' ,@Sort=120,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Not Approved',@Value='NTAPP' ,@Sort=130,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting OE Funding Release',@Value='AOEFR' ,@Sort=140,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Approved & PCS Review Minor Comment Change',@Value='APCSC' ,@Sort=150,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Partially Approved & PCS Review Minor Comment Change',@Value='APPCSC' ,@Sort=160,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Approved & Awaiting Minor Comment Change',@Value='AAMC' ,@Sort=170,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Partially Approved & Awaiting Minor Comment Change',@Value='APAMC',@Sort=180,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Migrated DMS Legacy',@Value='MIGR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting Final DM EP Approval',@Value='AFDMEPA',@CreatedBy='619704',@Active=0
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting Lead Planner Verification',@Value='ALPVERI',@CreatedBy='619704',@Active=0
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting PCS Class II & V',@Value='APWCP',@CreatedBy='619704',@Active=0
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Customer Not Approved',@Value='CNOTA',@CreatedBy='619704',@Active=0
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Processing Class II, V & P6 Schedule',@Value='PWPS',@CreatedBy='619704',@Active=0
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting PCS/OE Clarification',@Value='PCSCR',@CreatedBy='619704',@Active=1
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting PCS/OE Clarification',@Value='PCSCRPROG',@CreatedBy='619704',@Active=1
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Status',@Label='Awaiting OE Revised Commitments',@Value='AOERC',@CreatedBy='619704',@Active=1

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Status',@Label='Initiated',@Value='INIT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Status',@Label='Awaiting Verification',@Value='AVER',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Status',@Label='Awaiting OE Approval',@Value='AOEA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Status',@Label='Awaiting SM Approval',@Value='ASMA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Status',@Label='Awaiting DM EP Approval',@Value='ADPA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Status',@Label='Awaiting Customer Approval',@Value='ACAPP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Status',@Label='Approved and Completed',@Value='APPC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Status',@Label='Not Approved',@Value='NOTAPP',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Low Complexity Design Change',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Medium Complexity Design Change',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='High Complexity Design Change',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Mega Complexity Design Change',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Item Equivalency COTS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Low Complexity Pre-Engineered Change - COTS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Medium Complexity Pre-Engineered Change - COTS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='High Complexity Pre-Engineered Change - COTS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Mega Complexity Pre-Engineered Change - COTS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Item Equivalency - Custom',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Low Complexity Pre-Engineered Change - Custom',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Medium Complexity Pre-Engineered Change - Custom',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='High Complexity Pre-Engineered Change - Custom',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Mega Complexity Pre-Engineered Change - Custom',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Low Complexity Inspection & Maintenance',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Medium Complexity Inspection & Maintenance',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='High Complexity Inspection & Maintenance',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Complexity',@Label='Mega Complexity Inspection & Maintenance',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='Capital',@Value='CAP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='Small - Capital',@Value='SM-CAP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='Pre-Capital',@Value='Pre-CAP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='OMA',@Value='SM-BASE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='Initiative',@Value='OMAI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='Outage',@Value='Outage',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='CAPE',@Value='CAPE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='Capital Spares',@Value='CapS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='Fuel Handling',@Value='FH',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='FundingSource',@Label='Station',@Value='Station',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Initiation',@Value='0',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Conceptual Design (Development)',@Value='1',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Preliminary Design (Definition)',@Value='2',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Detailed Design (Preparation)',@Value='3',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Eng Construction Support (Execution)',@Value='4',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Phase',@Label='Closeout',@Value='5',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Execution',@Label='Online',@Value='ON',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Execution',@Label='Outage',@Value='OUT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='Execution',@Label='No Installation',@Value='NOINSTALL',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='BusinessDriver',@Label='Incremental Capital',@Value='INC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='BusinessDriver',@Label='Initiative',@Value='INI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='BusinessDriver',@Label='OMA',@Value='OMA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='SDQ',@Field='BusinessDriver',@Label='Sustaining Capital',@Value='SUS',@CreatedBy='619704'


EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Scope',@Value1='DED',@Label='Acts of nature (extreme weather, etc.)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Scope',@Value1='DED',@Label='Project scope of work change (project scope document)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Scope',@Value1='DED',@Label='Field discovery',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Scope',@Value1='DED',@Label='PMC/MCR managed design supplier delay (specify which supplier)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Scope',@Value1='DED',@Label='OEM documentation delay',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Scope',@Value1='DED',@Label='Regulatory delay (TSSA etc.)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Scope',@Value1='DED',@Label='Funding delay (per our assumed funding award date in the DQ)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Scope',@Value1='DED',@Label='Additional design required or schedule prioritization, caused by customer or customer managed group (specify cause and which group)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Trend',@Value1='DED',@Label='DED managed supplier delay (specify supplier)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Trend',@Value1='DED',@Label='Resource unavailable/insufficient (includes other design sections and drafting)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Trend',@Value1='DED',@Label='Design error/omission (Schedule error)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Trend',@Value1='DED',@Label='Design contract management issue',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='DVN',@Field='Reason',@Value2='Trend',@Value1='DED',@Label='Stakeholder review delay (includes non-DED stakeholders)',@CreatedBy='619704'

/*PBRF*/
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Initiated',@Value='INIT' ,@Sort=10,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Awaiting DM Approval',@Value='ADMA' ,@Sort=20,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Awaiting SM Approval',@Value='ASMA' ,@Sort=30,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Awaiting EBS Processing',@Value='AEBSP' ,@Sort=40,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Approved and Complete',@Value='APPC' ,@Sort=50,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Superceded',@Value='SUPER' ,@Sort=60,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Awaiting DivM Approval',@Value='ADIVM' ,@Sort=70,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Approved, Awaiting EBS',@Value='AAEBS' ,@Sort=80,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Correction Required',@Value='CORR' ,@Sort=90,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Canceled',@Value='CANC' ,@Sort=100,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Not Approved',@Value='NTAPP' ,@Sort=110,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Initial Correct Required',@Value='ICORR' ,@Sort=120,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='Status',@Label='Migrated DMS Legacy',@Value='MIGR',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='FundingSource',@Label='Cap Outage',@Value='CAP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='FundingSource',@Label='Large Capital',@Value='LAR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='FundingSource',@Label='OM&A',@Value='OMA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='FundingSource',@Label='OM&A Initiative',@Value='OMAI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='FundingSource',@Label='OM&A Outage',@Value='OMAO',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='FundingSource',@Label='Pre-Capital',@Value='PRE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='FundingSource',@Label='Small Capital',@Value='SMA',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1049',@Label='Fuel Handling & Tooling'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1050',@Label='Governance and Oversight'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1280',@Label='Bruce A Station Components'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1281',@Label='Bruce B Station Components'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1282',@Label='Equipment Reliability'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1353',@Label='Life Extension Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1439',@Label='Reactor Safety Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1440',@Label='Reactor Safety Support'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1442',@Label='Fuel and Physics'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1443',@Label='Probabilistic Safety Support'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1444',@Label='Reactor Safety Plant Support'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1446',@Label='Reactor Fuelling'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1447',@Label='Deterministic Safety Support'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1585',@Label='Design Services'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='1626',@Label='Fuel Handling'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2209',@Label='Fitness for Service'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2210',@Label='Nuclear Safety Analysis and'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2213',@Label='Reactor Safety Risk and'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2230',@Label='Component and Program'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2260',@Label='Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2263',@Label='Design Support Services'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2280',@Label='Engineering Business'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2281',@Label='Equipment Reliability'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2293',@Label='Nuclear Safety Analysis'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2421',@Label='Bruce A Fuel Handling'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2423',@Label='Bruce B Fuel Handling'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2568',@Label='Station Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2570',@Label='Bruce A Plant Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='2571',@Label='Bruce B Plant Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3230',@Label='EP Station Bruce B'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3235',@Label='EP Station Bruce A'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3244',@Label='Pressure Boundary and'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3273',@Label='Asset Management'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3274',@Label='Major Components'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3275',@Label='Mechanical Component'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3276',@Label='Civil/Security Design'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3277',@Label='Electrical/l&C Component'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3281',@Label='Bruce B Nuclear Systems'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3282',@Label='Bruce A Electrical/l&C'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3283',@Label='Bruce B Balance of Plant'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3284',@Label='Bruce B Electrical/l&C'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3286',@Label='Bruce A Nuclear Systems'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3287',@Label='Bruce A Balance of Plant'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3288',@Label='Site Services Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3289',@Label='Bruce B Rapid Response'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3290',@Label='Design Engineering Division'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3291',@Label='Mechanical Design'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3292',@Label='Control Design'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3293',@Label='Mechanical/Civil Drafting'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3294',@Label='Computer Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3295',@Label='Reactor Tooling and Fuel'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3296',@Label='Configuration Management'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3297',@Label='Reactor Design'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3298',@Label='Design Programs'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3299',@Label='Electrical Design'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3300',@Label='Configuration Management'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3450',@Label='Bruce A Rapid Response'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3471',@Label='Specialized Tool Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3620',@Label='Component Design'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3621',@Label='Component Design'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3740',@Label='Engineering Projects'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3741',@Label='Mechanical and Civil'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3742',@Label='l&C and  Electrical'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3744',@Label='Legacy Registration'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3745',@Label='Project Integration - Strategic'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3747',@Label='Project Integration'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3749',@Label='Engineering Project Controls '
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3751',@Label='Design Engineering Project '
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3761',@Label='ICE Projects'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='RC',@CreatedBy='619704',@Value='3762',@Label='MCD Projects'

EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='CustomerNeed',@CreatedBy='619704',@Value='ON',@Label='Online'
EXEC stng.SP_Common_CreateValueLabel @Module='PCC', @Group='PBRF',@Field='CustomerNeed',@CreatedBy='619704',@Value='OUT',@Label='Outage'