EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='FieldChangeLog',@Field='Field',@CreatedBy='619704',@Label='Modify'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='FieldChangeLog',@Field='Field',@CreatedBy='619704',@Label='Add'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='FieldChangeLog',@Field='Field',@CreatedBy='619704',@Label='Remove'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='FieldChangeLog',@Field='Options',@CreatedBy='619704',@Label='Modify'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='FieldChangeLog',@Field='Options',@CreatedBy='619704',@Label='Add'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='FieldChangeLog',@Field='Options',@CreatedBy='619704',@Label='Remove'

EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BA',@Label='0A'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BA',@Label='1'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BA',@Label='2'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BA',@Label='3'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BA',@Label='4'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BB',@Label='0B'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BB',@Label='5'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BB',@Label='6'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BB',@Label='7'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='BB',@Label='8'
EXEC stng.SP_Common_CreateValueLabel @Module='Common', @Group='Unit',@Field='SiteID',@CreatedBy='619704',@Value1='CS',@Label='Site Services'