EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='Status',@Label='Not Submitted',@Value='NOTSUB',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='Status',@Label='No Bid',@Value='NOBID' ,@Sort=20,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='Status',@Label='Submitted Editable',@Value='SUBEDIT' ,@Sort=30,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='Status',@Label='Submitted',@Value='SUBMIT',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Scope',@Label='Force Majeure (Acts of Nature)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Scope',@Label='Scope change (those that could not have been anticipated at the time of preparation of original task estimate)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Scope',@Label='Approach change (directed by customer)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Scope',@Label='Business drivers change (budget, deployment schedule, time constraints, business priorities, etc.)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Scope',@Label='Phase change of a project.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Scope',@Label='Variances created through the actions or lack of action by customers/PM.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Scope',@Label='Customers/PM provide incomplete or unstable requirements, adding new constraints, or through lack of timely decisions, work authorizations or contractual funding.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Trend',@Label='Changes that were/could have been anticipated during original task estimate.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Trend',@Label='Poor estimating, performance, risk or resource management.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Trend',@Label='Risk is encountered and mitigation steps need to be enacted.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Trend',@Label='Risk is encountered and estimate uncertainty dollars need to be spent.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Trend',@Label='Project cost projections are above a certain threshold.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Trend',@Label='Project is under budget or schedule.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Trend',@Label='Vendor is late on deliverable.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Trend',@Label='Resource is pulled from project.',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Reason',@Field='Trend',@Label='Re-sequence of implementation schedule (unless it costs more)',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='ASME NCA-4000 or CSA N285.0 CofA - Nuclear',@CreatedBy='619704',@Value='ASME'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='CAN/CSA-ISO 9001:2015',@CreatedBy='619704',@Value='CANCSA'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='CAN3-Z299.1-85 (R2007) or CSA N299.1-16',@CreatedBy='619704',@Value='CAN31'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='CAN3-Z299.2-85 (R2007) or CSA N299.2-16',@CreatedBy='619704',@Value='CAN32'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='CSA N286.7-16',@CreatedBy='619704',@Value='CSA'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='Other',@CreatedBy='619704',@Value='Other'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='No QA Requirements',@CreatedBy='619704',@Value='NoQA'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='ASME NCA-4000 or CSA N285.0 CofA - Nuclear',@CreatedBy='619704',@Value='ASME',@Value2='EMERGENT'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='CAN/CSA-ISO 9001:2015',@CreatedBy='619704',@Value='CANCSA',@Value2='EMERGENT'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='CAN3-Z299.1-85 (R2007) or CSA N299.1-16',@CreatedBy='619704',@Value='CAN31',@Value2='EMERGENT'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='CAN3-Z299.2-85 (R2007) or CSA N299.2-16',@CreatedBy='619704',@Value='CAN32',@Value2='EMERGENT'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='CSA N286.7-16',@CreatedBy='619704',@Value='CSA',@Value2='EMERGENT'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='Other',@CreatedBy='619704',@Value='Other',@Value2='EMERGENT'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='QA',@Label='No QA Requirements',@CreatedBy='619704',@Value='NoQA',@Value2='EMERGENT'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='WorkType',@Label='Standard Processing Time', @Value='STANARD',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='WorkType',@Label='Emergent Work', @Value='EMERGENT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='WorkType',@Label='Outage Short Term Impact', @Value='OUTAGE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='WorkType',@Label='H1 H2 Priority Work', @Value='PRIORITY',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='WorkType',@Label='Impact Critical Path', @Value='CRITICAL',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='WorkType',@Label='Non Emergent - Five day turn around', @Value='NONEMERG',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='Phase',@Label='Initiation',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='Phase',@Label='Conceptual Design (Development)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='Phase',@Label='Preliminary Design (Definition)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='Phase',@Label='Detailed Design (Preparation)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='Phase',@Label='Engr Construction Support (Execution)',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='Phase',@Label='Closeout',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorCorrespondence',@Field='QuestionType',@Label='Business',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorCorrespondence',@Field='QuestionType',@Label='Technical',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorCorrespondence',@Field='QuestionType',@Label='Date Extension',@Value1='DATEEXT',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='FundingType',@Label='T & M',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='FundingType',@Label='Fixed Price',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='ReasonForTOQ',@Label='Scope',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='ReasonForTOQ',@Label='Cost',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='ReasonForTOQ',@Label='Schedule',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='VendorSubmission',@Field='ReasonForTOQ',@Label='QA',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Initiated', @Value='INIT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting SM Initial Approval', @Value='ASMIA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting EBS Initial Acceptance', @Value='AEIA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting Vendor Submission', @Value='AVS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting OE Vendor Award', @Value='AOEVA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting SM Award Approval', @Value='ASAA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Hold For SDQ Funding', @Value='HOLDSF',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting LAMP Submission', @Value='ALAMS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting Commercial Review', @Value='ACOR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting Commercial Review', @Value='ACORF',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting SDQ Funding', @Value='ASDQF',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting OE Partial Input', @Value='AOEPI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting EBS SM Award Approval', @Value='AESAA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting DM EP Approval', @Value='ADMA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting Div M Approval', @Value='ADIVA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting EBS Final Processing', @Value='AEFP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Approved and Complete', @Value='ACC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Approved and Partial Release', @Value='APPR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Approved, Additional Partial Release in Progress', @Value='APR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Awaiting Partial Commercial Review', @Value='APCOR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Initial Correction Required', @Value='ICORR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Correction Required', @Value='CORR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Canceled', @Value='CANC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Closed', @Value='CLOSE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Not Approved', @Value='NTAPP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Replaced', @Value='REP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Revised', @Value='SUPER',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='StandardOE',@Field='Status',@Label='Deleted', @Value='DEL',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Initiated', @Value='INIT',@Sort=10,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting SM Initial Approval', @Value='ASMIA',@Sort=20,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting EBS Initial Acceptance', @Value='AEIA',@Sort=30,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting Vendor Submission', @Value='AVS',@Sort=40,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting OE Vendor Award', @Value='AOEVA',@Sort=50,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting SM Award Approval', @Value='ASAA',@Sort=60,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Hold For SDQ Funding', @Value='HOLDSF',@Sort=70,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting LAMP Submission', @Value='ALAMS',@Sort=80,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting Commercial Review', @Value='ACOR',@Sort=90,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting Commercial Review', @Value='ACORF',@Sort=100,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting SDQ Funding', @Value='ASDQF',@Sort=110,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting OE Partial Input', @Value='AOEPI',@Sort=120,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting EBS SM Award Approval', @Value='AESAA',@Sort=130,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting DM EP Approval', @Value='ADMA',@Sort=140,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting DM EP Approval', @Value='ADVMA',@Sort=145,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting Div M Approval', @Value='ADIVA',@Sort=150,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting EBS Final Processing', @Value='AEFP',@Sort=160,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Approved and Complete', @Value='ACC',@Sort=170,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Approved and Complete', @Value='ACCF',@Sort=175,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Approved and Partial Release', @Value='APPR',@Sort=180,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Approved, Additional Partial Release in Progress', @Value='APR',@Sort=190,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting Partial Commercial Review', @Value='APCOR',@Sort=200,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Initial Correction Required', @Value='ICORR',@Sort=210,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Correction Required', @Value='CORR',@Sort=220,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Canceled', @Value='CANC',@Sort=230,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Closed', @Value='CLOSE',@Sort=240,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Not Approved', @Value='NTAPP',@Sort=250,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Replaced', @Value='REP',@Sort=260,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Revised', @Value='SUPER',@Sort=270,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting EBS Processing', @Value='AEBSP',@Sort=45,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Hold for SDQ', @Value='HSDQ',@Sort=65,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting SVP Approval', @Value='ASVPA',@Sort=165,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Approved, Additional Partial Release in Progress', @Value='ADPR',@Sort=175,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting Cancellation Approval', @Value='ACANC',@Sort=225,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Awaiting SM Award Approval', @Value='AVSA',@Sort=225,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Approved and Complete', @Value='FULLR',@Sort=235,@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Deleted', @Value='DEL',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='CONSULT',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='MDCC',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='MDER',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='MDGEN',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='MDOE',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='MDSECC',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='REWORK',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STD',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='STDOE',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='SVN',@Field='Status',@Label='Approved, revision in progress', @Value='ARIP',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Request Denied (DM EP)',@Value='RDDMEP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Request Denied (Vendor)',@Value='RDV',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Resolved', @Value='RES',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Awaiting Vendor Acceptance',@Value='AVENA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Initiated', @Value='INIT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Awaiting DM EP Approval', @Value='ADMA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Approved and Complete', @Value='ACC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Cancelled', @Value='AVENA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Correction Required', @Value='CORR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='EMERG',@Field='Status',@Label='Deleted', @Value='DEL',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='CONSULT',@Field='Status',@Label='Awaiting SM Award Approval', @Value='AVSA',@CreatedBy='619704'

/**/
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Equipment Performance Subcategories', @Value1='EQUIPP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Electrical Distribution', @Value1='ELECT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='MPO', @Value1='ELECT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Power Conversion Equipment', @Value1='ELECT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Switch Yard', @Value1='ELECT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Protective Relay', @Value1='ELECT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Transformers', @Value1='ELECT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Fuel Handling', @Value1='FUELH',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Tooling', @Value1='FUELH',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Communications', @Value1='INSTR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Control System', @Value1='INSTR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Human Factors ', @Value1='INSTR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Conventional I&C', @Value1='INSTR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='DCC', @Value1='INSTR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Nuclear I&C', @Value1='INSTR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Fire Protection', @Value1='INSTR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Cranes', @Value1='MECHA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Heat Exchangers', @Value1='MECHA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Conventional Mechanical', @Value1='MECHA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Piping', @Value1='MECHA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Civil', @Value1='MECHA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Nuclear Mechanical', @Value1='MECHA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Air Systems and Compressors', @Value1='ROTAT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Pumps and Motors', @Value1='ROTAT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Turbine and Generator', @Value1='ROTAT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Air Operated Valve', @Value1='VALVE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Manual Valve', @Value1='VALVE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Motorized Valve', @Value1='VALVE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Electrical Distribution', @Value1='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Security', @Value1='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='COS', @Value1='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Analysis', @Value1='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Permits and Parts Ready', @Value1='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Governance and Oversight', @Value1='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Consulting', @Value1='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Emergent Work', @Value1='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='Project Management', @Value1='PROJM',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='ELECT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='EQUIPP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='ELECT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='FUELH',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='INSTR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='MECHA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='PROJM',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='ROTAT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='SubWorkType',@Label='N/A', @Value1='VALVE',@CreatedBy='619704'


EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Civil', @Value='CIVIL',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='DCC', @Value='DCC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Electrical Equipment', @Value='ELECT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Emergent Work', @Value='EMERG',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='EQ Engineering, CGD', @Value='EQENG',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Fuel Handling', @Value='FUELH',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Generic Permit', @Value='GPERM',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='I&C Quality Software', @Value='ICQSO',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Instrument & Control', @Value='INSTR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Internal', @Value='INTER',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Mechanical Equipment', @Value='MECHA',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Niche Fire Protection', @Value='NICEF',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Rotating Equipment', @Value='ROTAT',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Specialized Engineering', @Value='SPECI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Valve', @Value='VALVE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Equipment Performance', @Value='EQUIPP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Vendor',@Field='WorkType',@Label='Project Management', @Value='PROJM',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='ScopeManagedBy',@Label='PMC', @Value='PMC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='ScopeManagedBy',@Label='DED', @Value='DED',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='ScopeManagedBy',@Label='MCR', @Value='MCR',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='ScopeManagedBy',@Label='SE', @Value='SE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='ScopeManagedBy',@Label='RS', @Value='RS',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Header',@Field='ScopeManagedBy',@Label='Other', @Value='Other',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='Capital', @Value='CAPITAL',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='CAPE', @Value='CAPE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='Capital Spares', @Value='CAPSPARES',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='Outage', @Value='OUTAGE',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='Pre-Capital Projects', @Value='PRECAP',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='Fuel Handling', @Value='FUELHD',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='Small Project - Base', @Value='SPRJB',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='OM&A Initiative', @Value='OMAI',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='Small Project - Captialized', @Value='SPRJC',@CreatedBy='619704'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ',@Group='Header',@Field='FundingSource',@Label='Station', @Value='STATION',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Standard',@Value='STD',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Standard OE/ADE',@Value='STDOE',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Mini-drawdown (Core Consulting)',@Value='MDCC',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Parent SA',@Value='PSA',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Emergent',@Value='EMERG',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Mini-drawdown (OE/ADE)',@Value='MDOE',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Mini-drawdown (ER)',@Value='MDER',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Mini-drawdown (General)',@Value='MDGEN',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Mini-drawdown (Section Consulting)',@Value='MDSECC',@CreatedBy='619704'	
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='Consulting',@Value='CONSULT',@CreatedBy='619704'		
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='Record',@Field='Type',@Label='SVN',@Value='SVN',@CreatedBy='619704'

EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='Resource',@CreatedBy='619704',@Label='Internal'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='Resource',@CreatedBy='619704',@Label='External'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='Complexity',@CreatedBy='619704',@Label='Low'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='Complexity',@CreatedBy='619704'	,@Label='Medium'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='Complexity',@CreatedBy='619704',@Label='High'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Project Initiation'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Conceptual Design Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Preliminary Design Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Detailed Design Engineering Control Design'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Computer Design'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Civil Design'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Reactor Design'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Electrical Design'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='HF & Fire & Tooling'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Mechanical Design'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Design Processes'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Generic to all disciplines'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Installation'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Closeout'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='VTIPs, SCRs, EIR'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Project Management/Project Controls'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Environmental Qualification'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Procurement Engineering'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Consulting'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBS',@CreatedBy='619704',@Label='Managed Services'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Project Number Set-up',@Value1='5',@Value2='0'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Resource Allocation',@Value1='10',@Value2='0'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Conceptual Design Engineering Plan',@Value1='85',@Value2='107'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Prepare DQ',@Value1='20',@Value2='0'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='OPEX Review',@Value1='14',@Value2='18'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Perform Risk Assessment',@Value1='7',@Value2='9'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Walkdown Report',@Value1='20',@Value2='25'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Draft FMEA Report',@Value1='38',@Value2='35'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Prepare/Update System Design Requirements',@Value1='65',@Value2='82'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Conceptual Design Report',@Value1='135',@Value2='169'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Issue Design Plan for Preliminary Engineering',@Value1='80',@Value2='100'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Revise DQ for next phase',@Value1='20',@Value2='0'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Package',@Value1='200',@Value2='250'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Prepare Technical Specifications',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Update System Design Requirements',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Update Draft FMEA Report',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='WARR DCNs',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Supply Chain Support for Equipment Procurement',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Issue Design Plan for Detailed Engineering',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Revise DQ for next phase',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice - I&C',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice - Software',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Device Specification',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Calibration Specification',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Uncertainity Calculation',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Configuration Intent Change',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice - Hardware',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice - Software',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Calibration Specification',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Configuration Intent Change',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice - Civil',@Value1='',@Value2=''
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Civil Calculations'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Seismic Assessment - Testing'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Seismic Assessment - Walkdown'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Configuration Intent Change'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice - Reactor Design'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='SCL update (BP-PROC-00320)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Stress Analysis'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Code Classification Internal (DIV-ENG-00017)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Code Classification External (DIV-ENG-00017)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Legacy Registration'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Registration (DIV-ENG-00018)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Reconciliation registration not required (nuclear) (DIV-ENG-00018)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Configuration Intent Change'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice - Elec'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Electrical Calculations'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Device Specification'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Calibration Specification'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Uncertainity Calculation'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Configuration Intent Change'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice - Software'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Device Specification'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Calibration Specification'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Instrument Uncertainity Calculation'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Human Factors Minor'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Human Factors Major'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Fire Protection Third Party Review'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Fire Protection FHA/FSSA Updates'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Configuration Intent Change'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Change Notice - Mech'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='SCL update (BP-PROC-00320)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Stress Analysis'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Code Classification Internal (DIV-ENG-00017)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Code Classification External (DIV-ENG-00017)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Legacy Registration'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Registration (DIV-ENG-00018)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Reconciliation registration not required (nuclear) (DIV-ENG-00018)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Configuration Intent Change'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Project Initiation'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Development Concept'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Definition (Preliminary)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Preparation (Procedure)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Preparation (Training)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Execution - Implementation (Cutover)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Turnover'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Closeout'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Update FMEA Report'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='O&M Documentation'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Manual Update (ADL for the DCP)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Commissioning Specification'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Vendor Docs'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Plan for Installation/Commissioning'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Revise DQ for next phase'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Pre-Installation Support - Design'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Installation/Commissioning/AFS Support - Design'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Installation/Commissioning/AFS - Computers'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Pre-Installation Support - FTL'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Installation/Commissioning/AFS/TMOD Removal  Support - FTL'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='DCN Closeout'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='DCP Closeout'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Project Closeout'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Engineering Information Request'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Vendor concession application'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Vendor  Drawings'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='SCRs'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Engineering Decision Memo'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Technical Operability Evaluation'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Root Cause Investigation'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Replacement Instructions'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='EQE'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='EQD'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='EQA'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Tech Spec'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Calc (required for RVs only)'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Bids'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Concession'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Design Report'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Drawing'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Procedure'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Item Equivalency Evaluation'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Project Management'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Project Controls'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Consulting'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Managed Services'
EXEC stng.SP_Common_CreateValueLabel @Module='TOQ', @Group='ClassV',@Field='WBSDetail',@CreatedBy='619704',@Label='Permit'
