variables:
  - group: DEVVars

pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - DEV

steps:
  # Install .NET 8 SDK
  - task: UseDotNet@2
    displayName: "Install .NET SDK"
    inputs:
      packageType: "sdk"
      version: "8.0.105"

  # Login to ACR
  - task: Docker@2
    displayName: "Docker Login to ACR"
    inputs:
      command: "login"
      containerRegistry: "ServConn-DockerRegistrySPN-DEVQA"

  # Debug - Check environment variables
  - script: |
      echo "CONTAINERNAME: $CONTAINERNAME"
      echo "ENVNAME: $ENVNAME"
    displayName: "Debug Environment Variables"
    env:
      CONTAINERNAME: $(AppServiceName)
      ENVNAME: $(EnvName)

  # Build Docker image with build args and tags
  - task: Docker@2
    displayName: "Build Docker Image"
    inputs:
      command: build
      repository: $(AppServiceName)/stable
      containerRegistry: "ServConn-DockerRegistrySPN-DEVQA"
      dockerfile: "Dockerfile"
      buildContext: "$(System.DefaultWorkingDirectory)"
      arguments: --build-arg ENVNAME=$(EnvName) --build-arg CONTAINERNAME=$(AppServiceName)
      tags: |
        latest

  # Push Docker image to ACR
  - task: Docker@2
    displayName: "Push Docker Image"
    inputs:
      command: push
      repository: $(AppServiceName)/stable
      containerRegistry: "ServConn-DockerRegistrySPN-DEVQA"
      tags: |
        latest

  # Restart Azure App Service
  - task: AzureCLI@2
    displayName: "Restart Azure Web App"
    inputs:
      azureSubscription: $(DevOpsServiceName)
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: |
        $currentattempt = 1
        $attempts = 3
        while ($currentattempt -le $attempts) {
          az webapp restart -n $(AppServiceName) -g $(RG)
          if ($LASTEXITCODE -eq 0) {
            Write-Host "Successfully restarted $(AppServiceName)"
            break
          }
          $currentattempt++
          Start-Sleep -Seconds 5
        }
