CREATE OR ALTER VIEW [stng].[VV_MPL_SC]
AS
SELECT   
					'SC' AS ProjectDepartment,
						mpl.INTERNALID as INTERNALID,
						PROJECTID, 
						PROJECTIDNUM AS SharedProjectID,
						PROJECTNAME, 
						BUSINESSDRIVER,
						BUYERANALYST, 
						BUYERANALYSTSHORT AS BuyerAnalystLANID,
						PROJECTCATEGORYSHORT AS Category, 
                         CONTRACTADMIN, 
						 CONTRACTADMINSHORT AS ContractAdminLANID,
						 CONTRACTTYPE, PROJECTCOSTANALYST AS CostAnalyst,
						 PROJECTCOSTANALYSTSHORT AS CostAnalystLANID, CSFLM, 
						 CSFLMSHORT AS CSFLMLANID, 
                         PCS, PCSSHORT AS PCSLANID, 
						 DEPARTMENT,
						 DISCIPLINE,
						 FASTTRACK, 
						 FUNDINGSOURCE,
						 MATERIALBUYER,
						 MATERIALBUYERSHORT AS MaterialBuyerLANID,
						 MULTIDISC, OWNERSENGINEER, 
                         OWNERSENGINEERSHORT AS OwnersEngineerLANID,
						 PORTFOLIO, 
						 PHASE, 
						 PROGRAM, 
						 PROGRAMMANAGER,
						 PROGRAMMANAGERSHORT AS ProgramManagerLANID,
						 PROJECTENGINEER, 
                         PROJECTENGINEERSHORT AS ProjectEngineerLANID,
						 PROJECTMANAGER,
						 PROJECTMANAGERSHORT AS ProjectManagerLANID,
						 PROJECTPLANNER, 
						 PROJECTPLANNERSHORT AS ProjectPlannerLANID, 
                         PROJECTPLANNERALTERNATE, 
						 PROJECTPLANNERALTERNATESHORT AS ProjectPlannerAlternateLANID, 
						 SENIORPROGRAMMANAGER, 
						 SENIORPROGRAMMANAGERSHORT AS SeniorProgramManagerLANID, 
						 SERVICEBUYER, 
                         SERVICEBUYERSHORT AS ServiceBuyerLANID, 
						 STATUS,
						 SUBPORTFOLIO,
						 PROJECTTYPE
						 ,[COMMERCIALMANAGER]
						 ,[COMMERCIALMANAGERSHORT]
FROM            stng.MPL AS mpl
WHERE        (PROJECTID LIKE '%CS%')
GO


