CREATE OR ALTER VIEW [stng].[VV_TWP_Details] AS
SELECT e.PARENTTASK, e.TASK_ID, e.CHILDACTIVITYID, e.CHILDACTIVITYNAME, e.CHILDACTSTARTDATE, e.CHILDACTENDDATE, 
e.CHILDTARGETSTARTDATE, e.CHILDTARGETENDDATE, e.COMPLETED, e.RESOURCEID, e.RESPORG, e.ROLEID, e.UniqueID, 
case when f.Flagged is null then 0 else f.Flagged end as Flagged, e.OUTAGE, e.MAJORGROUP
FROM  stngetl.TWP_TaskChild AS e 
left JOIN stngetl.TWP_TaskChildFlags as f ON e.PARENTTASK = f.PARENTTASK and e.TASK_ID = f.TASK_ID
GO


