CREATE OR ALTER VIEW [stng].[VV_Budgeting_Main] as 
	SELECT 
		'SDQ' AS [Type],
		[UniqueID],
		[RecordTypeUniqueID],
		CAST([RecordID] AS VARCHAR(50)) AS RecordID,
		CAST([Revision] AS VARCHAR(20)) AS Revision,
		SubRevision,
		LatestRevision,
		CAST(NULL AS VARCHAR(50)) AS [ParentPBRUID],
		[ProjectNo],
		[ProjectTitle],
		[ProjectStatus],
		[TargetDMApprovalDate],
		[TargetExecutionWindow],
		CAST([StatusID] AS VARCHAR(50)) AS [StatusID],
		[Status],
		[StatusValue],
		CurrentStatusDate,
		[RequestDate],
		[RequestFrom],
		[RequestFromID],
		[PCS],
		[PCSID],
		[OE],
		[OEID],
		[Planner],
		[PlannerID],
		[ProjM],
		[ProjMID],
		[ProgMID],
		[ProgM],
		[Section],
		[SMID],
		[SM],
		[DMID],
		[DM],
		[DivMID],
		[DivM],
		DMEPID,
		DMEP,
		[FundingSourceID],
		FundingSource,
		NULL ProjectTypeID,
		CAST(NULL AS VARCHAR(100)) AS [RC],
		CAST(NULL AS VARCHAR(50)) AS [RCID],
		CAST(NULL AS VARCHAR(MAX)) AS [Objective],
		CAST(NULL AS VARCHAR(MAX)) AS [CustomerNeed],
		CAST(NULL AS DATETIME) AS [CustomerNeedDate],
		CAST(NULL AS VARCHAR(50)) AS [CustomerNeedID],
		Phase,
		PhaseDescription,
		PrimaryDiscipline,
		ComplexityID,
		PreviouslyApproved,
		RequestedScope,
		VarianceComment,
		CreatedBy,
		Verifier,
		VerifierID,
		CAST(NULL AS VARCHAR(MAX)) AS [InfoRef],
		CAST(NULL AS VARCHAR(100)) AS Station,
		CAST(NULL AS VARCHAR(50)) AS [Total],
		CAST(NULL AS VARCHAR(50)) AS [Year1],
		CAST(NULL AS VARCHAR(50)) AS [Internal1],
		CAST(NULL AS VARCHAR(50)) AS [External1],
		CAST(NULL AS VARCHAR(50)) AS [Year2],
		CAST(NULL AS VARCHAR(50)) AS [Internal2],
		CAST(NULL AS VARCHAR(50)) AS [External2],
		PendingApprovers,
		Legacy,
		RecordTypeUniqueID AS SDQUID,
		LAMP3,
		HasP6,
		CAST(NULL AS DATETIME) AS SMApprovalDate,
		DMApprovalDate,
		CAST(NULL AS DATETIME) AS DivMApprovalDate,
		CAST(LAMP4 AS VARCHAR(50)) AS LAMP4,
		CAST(LAMP4Baseline AS VARCHAR(50)) AS LAMP4Baseline,
		CAST(NULL AS VARCHAR(500)) AS SMAll,
		RevisionHeader,
		HasApprovedSDQ
	FROM stng.VV_Budgeting_SDQMain

	UNION ALL 

	SELECT 
		'PBRF' AS [Type],
		[UniqueID],
		[RecordTypeUniqueID],
		CAST([RecordID] AS VARCHAR(50)) AS RecordID,
		CAST([Revision] AS VARCHAR(20)) AS Revision,
		CAST(NULL AS INT) AS SubRevision,
		CAST(NULL AS BIT) AS LatestRevision,
		CAST([ParentPBRUID] AS VARCHAR(50)) AS [ParentPBRUID],
		[ProjectNo],
		[ProjectTitle],
		CAST(NULL AS VARCHAR(50)) AS [ProjectStatus],
		CAST(NULL AS DATETIME) AS [TargetDMApprovalDate],
		CAST(NULL AS VARCHAR(100)) AS [TargetExecutionWindow],
		CAST([StatusID] AS VARCHAR(50)) AS [StatusID],
		[Status],
		[StatusValue],
		CurrentPBRStatusDate AS [CurrentStatusDate],
		[RequestDate],
		[RequestFrom],
		[RequestFromID],
		CAST(NULL AS VARCHAR(100)) AS [PCS],
		CAST(NULL AS VARCHAR(50)) AS [PCSID],
		CAST(NULL AS VARCHAR(100)) AS [OE],
		CAST(NULL AS VARCHAR(50)) AS [OEID],
		CAST(NULL AS VARCHAR(100)) AS [Planner],
		CAST(NULL AS VARCHAR(50)) AS [PlannerID],
		CAST(NULL AS VARCHAR(100)) AS [ProjM],
		CAST(NULL AS VARCHAR(50)) AS [ProjMID],
		CAST(NULL AS VARCHAR(50)) AS [ProgMID],
		CAST(NULL AS VARCHAR(100)) AS [ProgM],
		[Section],
		[SMID],
		[SM],
		[DMID],
		[DM],
		[DivMID],
		[DivM],
		CAST(NULL AS VARCHAR(50)) AS DPTEPDMID,
		CAST(NULL AS VARCHAR(100)) AS DPTEPDM,
		[FundingSourceID],
		FundingSource,
		ProjectTypeID,
		[RC],
		[RCID],
		[Objective],
		[CustomerNeed],
		[CustomerNeedDate],
		[CustomerNeedID],
		CAST(NULL AS INT) AS Phase,
		CAST(NULL AS VARCHAR(100)) AS PhaseDescription,
		CAST(NULL AS VARCHAR(100)) AS PrimaryDiscipline,
		CAST(NULL AS VARCHAR(50)) AS ComplexityID,
		CAST(NULL AS BIT) AS PreviouslyApproved,
		CAST(NULL AS INT) AS RequestedScope,
		CAST(NULL AS VARCHAR(MAX)) AS VarianceComment,
		RequestFromID AS CreatedBy,
		CAST(NULL AS VARCHAR(100)) AS Verifier,
		CAST(NULL AS VARCHAR(50)) AS [VerifierID],
		InformationReferences AS InfoRef,
		Station,
		CAST([Total] AS VARCHAR(50)) AS [Total],
		CAST([Year1] AS VARCHAR(50)) AS [Year1],
		CAST([Internal1] AS VARCHAR(50)) AS [Internal1],
		CAST([External1] AS VARCHAR(50)) AS [External1],
		CAST([Year2] AS VARCHAR(50)) AS [Year2],
		CAST([Internal2] AS VARCHAR(50)) AS [Internal2],
		CAST([External2] AS VARCHAR(50)) AS [External2],
		CAST(NULL AS VARCHAR(MAX)) AS PendingApprovers,
		CAST(0 AS BIT) AS Legacy,
		CAST(NULL AS VARCHAR(50)) AS SDQUID,
		CAST(NULL AS DECIMAL) AS LAMP3,
		CAST(NULL AS BIT) AS HasP6,
		SMApprovalDate,
		DMApprovalDate,
		DivMApprovalDate,
		CAST(NULL AS VARCHAR(50)) AS LAMP4,
		CAST(NULL AS VARCHAR(50)) AS LAMP4Baseline,
		CAST(NULL AS VARCHAR(500)) AS SMAll,
		CAST(NULL AS VARCHAR(500)) AS RevisionHeader,
		CAST(NULL AS BIT) AS HasApprovedSDQ
	FROM stng.VV_Budgeting_PBRFMain

	UNION ALL

	SELECT 
		'DVN' AS [Type],
		CONCAT('DVN-(SDQ-',SDQUID,')-',DVNNumber) AS [UniqueID],
		CAST(NULL AS VARCHAR(50)) AS [RecordTypeUniqueID],
		CAST(DVNID AS VARCHAR(50)) AS [RecordID],
		CAST([DVNNumber] AS VARCHAR(20)) AS Revision,
		CAST(NULL AS INT) AS [SubRevision],
		CAST(NULL AS BIT) AS LatestRevision,
		CAST(NULL AS VARCHAR(50)) AS [ParentPBRUID],
		ProjectID AS [ProjectNo],
		PROJECTNAME AS [ProjectTitle],
		CAST(NULL AS VARCHAR(50)) AS [ProjectStatus],
		CAST(NULL AS DATETIME) AS [TargetDMApprovalDate],
		CAST(NULL AS VARCHAR(100)) AS [TargetExecutionWindow],
		CAST(DVNStatusID AS VARCHAR(50)) AS [StatusID],
		DVNStatus AS [Status],
		DVNStatusShort AS [StatusValue],
		DVNStatusDate AS CurrentStatusDate,
		CreatedDate AS [RequestDate],
		PreparerName AS [RequestFrom],
		Preparer AS [RequestFromID],
		PCSName AS [PCS],
		PCS AS [PCSID],
		OEName AS [OE],
		OE AS [OEID],
		CAST(NULL AS VARCHAR(100)) AS [Planner],
		CAST(NULL AS VARCHAR(50)) AS [PlannerID],
		PMName AS [ProjM],
		PM AS [ProjMID],
		CAST(NULL AS VARCHAR(50)) AS [ProgMID],
		CAST(NULL AS VARCHAR(100)) AS [ProgM],
		CAST(NULL AS VARCHAR(100)) AS [Section],
		SM AS [SMID],
		SMName AS SM,
		DM AS [DMID],
		DMName AS [DM],
		CAST(NULL AS VARCHAR(50)) AS [DivMID],
		CAST(NULL AS VARCHAR(100)) AS [DivM],
		DPTEPDM AS DPTEPDMID,
		DPTEPDMName AS DPTEPDM,
		CAST(NULL AS VARCHAR(50)) AS FundingSourceID,
		CAST(NULL AS VARCHAR(100)) AS FundingSource,
		CAST(NULL AS VARCHAR(50)) AS [ProjectTypeID],
		CAST(NULL AS VARCHAR(100)) AS [RC],
		CAST(NULL AS VARCHAR(50)) AS [RCID],
		CAST(NULL AS VARCHAR(MAX)) AS [Objective],
		CAST(NULL AS VARCHAR(MAX)) AS [CustomerNeed],
		CAST(NULL AS DATETIME) AS [CustomerNeedDate],
		CAST(NULL AS VARCHAR(50)) AS [CustomerNeedID],
		CAST(NULL AS INT) AS Phase,
		CAST(NULL AS VARCHAR(100)) AS PhaseDescription,
		CAST(NULL AS VARCHAR(100)) AS PrimaryDiscipline,
		CAST(NULL AS VARCHAR(50)) AS ComplexityID,
		CAST(NULL AS BIT) AS PreviouslyApproved,
		CAST(NULL AS INT) AS RequestedScope,
		CAST(NULL AS VARCHAR(MAX)) AS VarianceComment,
		Preparer AS CreatedBy,
		VerifierName AS [Verifier],
		Verifier AS [VerifierID],
		CAST(NULL AS VARCHAR(MAX)) AS InformationReferences,
		CAST(NULL AS VARCHAR(100)) AS Station,
		CAST(NULL AS VARCHAR(50)) AS [Total],
		CAST(NULL AS VARCHAR(50)) AS [Year1],
		CAST(NULL AS VARCHAR(50)) AS [Internal1],
		CAST(NULL AS VARCHAR(50)) AS [External1],
		CAST(NULL AS VARCHAR(50)) AS [Year2],
		CAST(NULL AS VARCHAR(50)) AS [Internal2],
		CAST(NULL AS VARCHAR(50)) AS [External2],
		CAST(NULL AS VARCHAR(MAX)) AS PendingApprovers,
		LegacySDQ AS Legacy,
		SDQUID,
		CAST(NULL AS DECIMAL) AS LAMP3,
		CAST(NULL AS BIT) AS HasP6,
		CAST(NULL AS DATETIME) AS SMApprovalDate,
		CAST(NULL AS DATETIME) AS DMApprovalDate,
		CAST(NULL AS DATETIME) AS DivMApprovalDate,
		CAST(NULL AS VARCHAR(50)) AS LAMP4,
		CAST(NULL AS VARCHAR(50)) AS LAMP4Baseline,
		CAST(NULL AS VARCHAR(500)) AS SMAll,
		CAST(NULL AS VARCHAR(500)) AS RevisionHeader,
		CAST(NULL AS BIT) AS HasApprovedSDQ
	FROM stng.VV_Budgeting_DVN
	WHERE DVNStatusShort NOT IN ('CAN');
GO