CREATE TABLE stng.Budgeting_SDQRelatedTOQ
(
	UniqueID UNIQUEIDENTIFIER DEFAULT NEWID(),
	SDQUID BIGINT REFERENCES stng.Budgeting_SDQMain(SDQUID),
	TOQUID UNIQUEIDENTIFIER REFERENCES stng.TOQ_Main(UniqueID),
	ApprovedAmount INT DEFAULT 0,
	CreatedDate DATETIME DEFAULT stng.GetDate(),
	CreatedBy VARCHAR(20)
)