CREATE TABLE stng.Budgeting_SDQP6Link
(
	UniqueID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	SDQUID BIGINT REFERENCES stng.Budgeting_SDQMain(SDQUID),
	RunID UNIQUEIDENTIFIER REFERENCES stngetl.Budgeting_SDQ_Run(RunID),
	Active BIT DEFAULT 0,
	CreatedDate DATETIME DEFAULT stng.GetDate(),
	CreatedBy VARCHAR(20)
)